[source.db1]
host = "127.0.0.1"
port = 33061
username = "root"
password = "rootpass"

[target.db2]
source = "source.db1"
host = "127.0.0.1"
port = 33062
username = "root"
password = "rootpass"

[source.db3]
host = "127.0.0.1"
port = 33063
username = "root"
password = "rootpass"

[target.db4]
source = "source.db3"
host = "127.0.0.1"
port = 33064
username = "root"
password = "rootpass"

[source.db5]
host = "127.0.0.1"
port = 33065
username = "root"
password = "rootpass"

[target.db6]
source = "source.db5"
host = "127.0.0.1"
port = 33066
username = "root"
password = "rootpass"

[schemas.ignore]
names = ["sys", "mysql", "information_schema", "performance_schema"]

